---
title: "Gov 50 Final Project"
author: "Heidi Enger"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to U.S. elections, including topics such as online misinformation, voting demographics, and voter turnout. I'm especially interested in examining voter turnout in states which have passed restrictive voting laws in the aftermath of the 2013 Shelby County v. Holder Supreme Court case, which found Section 4 of the Voting Rights Act unconstitutional, allowing states to pass voting laws without being subject to federal review. Restrictive laws include restrictions on mail voting and unreasonably strict voter ID requirements, which disproportionately impact voters of color. These sorts of laws have been adopted by 29 states to date (https://www.brennancenter.org/our-work/analysis-opinion/states-have-added-nearly-100-restrictive-laws-scotus-gutted-voting-rights).

## Proposal

Did restrictive state voting laws after Shelby County vs. Holder (2013) impact voter turnout in the 2016 general election? In this project, I will examine the extent to which restrictive voting laws passed after the Shelby decision impacted voter turnout in applicable states. I hypothesize that voter turnout decreased from 2012 to 2016 in states which passed stricter voter ID and mail-in ballot laws, especially for voters of color. I've chosen a data set with election data from 1948-2020, though I'll only be looking at general election data from 2012 and 2016, since I want to compare across time. The explanatory variable of interest is whether a state passed  restrictive voting law(s) or not. I will need to filter to specific states from the data based on information from the Brennan Center (see above). My outcome variable is voter turnout in a given state. If I observe lower voter turnout in 2016 compared to 2012 in states which passed restrictive voting laws, this would provide support for my hypothesis. If I observe higher or similar voter turnout, this would provide evidence against my hypothesis. 


```{r}
library(tidyverse)
library(readr)
elections <- read_csv("anes_timeseries.csv")


```

